// await page.locator('div').filter({ hasText: 'Okres Naciśnij enter aby rozwinąć. Użyj strzałek aby zmienić pozycję. Spację aby' }).nth(4).click();
// await page.getByRole('option', { name: 'Ostatni rok' }).locator('label').click();
// await page.getByText('Jednostka administracji Naciśnij enter aby rozwinąć. Użyj strzałek aby zmienić p').click();
// await page.getByPlaceholder('szukaj...').click();
// await page.getByPlaceholder('szukaj...').fill('cyfrowa');
// await page.getByRole('option', { name: 'Cyfrowa Piaskownica Administracji' }).locator('label').click();
// await page.getByRole('option', { name: 'Cyfrowa Piaskownica Administracji' }).locator('label').click();
// await page.getByPlaceholder('szukaj...').click();
// await page.getByPlaceholder('szukaj...').fill('biuletyn ');
// await page.getByRole('option', { name: 'Biuletyn Informacji Publicznej' }).locator('label').click();